# Generated by Django 4.0.4 on 2022-05-17 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visite', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lieu',
            old_name='Pays',
            new_name='pays',
        ),
        migrations.AlterField(
            model_name='lieu',
            name='visite_par_an',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Monuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_monument', models.CharField(max_length=100)),
                ('adresse_monument', models.CharField(max_length=100)),
                ('date_construction', models.DateField(blank=True, null=True)),
                ('lieu', models.ForeignKey(null='true', on_delete=django.db.models.deletion.CASCADE, to='visite.lieu')),
            ],
        ),
    ]
