# Generated by Django 4.0.4 on 2022-05-17 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visite', '0002_rename_pays_lieu_pays_alter_lieu_visite_par_an_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monuments',
            name='lieu',
        ),
        migrations.AddField(
            model_name='lieu',
            name='monuments',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='visite.monuments'),
        ),
    ]
