# Generated by Django 4.0.4 on 2022-05-18 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visite', '0003_remove_monuments_lieu_lieu_monuments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lieu',
            name='monuments',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='visite.monuments'),
        ),
    ]
