# Generated by Django 4.0.4 on 2022-05-21 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visite', '0004_alter_lieu_monuments'),
    ]

    operations = [
        migrations.AddField(
            model_name='lieu',
            name='image_ville',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='monuments',
            name='image_monument',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='lieu',
            name='monuments',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='visite.monuments'),
        ),
        migrations.AlterField(
            model_name='lieu',
            name='periode_moins_visite',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='lieu',
            name='periode_plus_visite',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
