# Generated by Django 4.0.4 on 2022-05-21 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visite', '0005_lieu_image_ville_monuments_image_monument_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lieu',
            name='monuments',
        ),
        migrations.AddField(
            model_name='monuments',
            name='lieu',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='visite.lieu'),
        ),
    ]
